### PR TITLE
Feature/faq content

### PR DESCRIPTION
**Pull request by valanex**
Added 4 questions and answers to the FAQ page to replace placeholder content.

### CODE REVIEW

**Comment by MoxElliot** [comment]
image

questions run into footer

**Comment by E-wang42** [comment]
_Please fix_
image

**Please change mb-5 to mb-12 in line 38.  This will spread out the containers more evenly in mobile view.** 
Untitled1

**Comment by valanex** [comment]
- Margin increased to spread containers farther apart.
- Fixed bug with expanded containers running into footer

**Comment by E-wang42** [comment]
Please fix white space in mobile view

image

**Review by E-wang42 — APPROVED** [review]
noice

**Pull request merged**
