### PR TITLE
Feature Faq page UI & functionality

### PR DESCRIPTION
**Pull request by Danneytrieu**
*Re-created PR to setup merge from working branch -> development branch

### CODE REVIEW

**Comment by MoxElliot** [comment]
1. Hand Pointer is on the entire question, but only expands the question when clicking the right icon or directly under the text
a. Change to the question expands when user clicks anywhere on the banner (or have the pointer only when the are is expandable?)
image

2. Cursor appears anywhere user clicks on page text. Is this working as expected? I've never noticed it before but maybe its my browser setting?
image

**Comment by Danneytrieu** [comment]
Good catch man, i fixed the cursor pointer issue and the 2nd issue you mentioned is working as expected, could be browser issue. 

> 1. Hand Pointer is on the entire question, but only expands the question when clicking the right icon or directly under the text
>    a. Change to the question expands when user clicks anywhere on the banner (or have the pointer only when the are is expandable?)
>    image
> 2. Cursor appears anywhere user clicks on page text. Is this working as expected? I've never noticed it before but maybe its my browser setting?
>    image

**Comment by E-wang42** [comment]
padding

please fix padding

**Review by MoxElliot — APPROVED** [review]
Fixed merge conflict and closed a css tag

**Pull request merged**
